name: Discord Mudae Automation

on:
  schedule:
    - cron: "0 5 * * *"  # Runs at 05:00 UTC, corresponding to midnight EST
    - cron: "0 17 * * *"  # Runs at 17:00 UTC, corresponding to noon EST

permissions:
  contents: read

jobs:
  automate_discord_mudae:
    runs-on: ubuntu-latest  # Use an Ubuntu environment for running the script

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies (e.g., selenium)
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Mudae automation script
        env:
          DISCORD_EMAIL: ${{ secrets.DISCORD_EMAIL }}
          DISCORD_PASS: ${{ secrets.DISCORD_PASS }}
          DISCORD_CHANNEL: ${{ secrets.DISCORD_CHANNEL }}
        run: |
          python daily_mudae_automation.py  # Run your Python script
